DROP TABLE IF EXISTS nba_players;

CREATE TABLE nba_players (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    team VARCHAR(100) NOT NULL,
    position VARCHAR(50),
    height VARCHAR(10),
    weight INTEGER
);

INSERT INTO nba_players (name, team, position, height, weight) VALUES
('LeBron James', 'Los Angeles Lakers', 'SF', '6''9"', 250),
('Kevin Durant', 'Phoenix Suns', 'SF', '6''10"', 240),
('Stephen Curry', 'Golden State Warriors', 'PG', '6''2"', 185),
('Giannis Antetokounmpo', 'Milwaukee Bucks', 'PF', '6''11"', 242),
('James Harden', 'Philadelphia 76ers', 'SG', '6''5"', 220),
('Luka Dončić', 'Dallas Mavericks', 'PG', '6''7"', 230),
('Kawhi Leonard', 'Los Angeles Clippers', 'SF', '6''7"', 225),
('Anthony Davis', 'Los Angeles Lakers', 'PF', '6''10"', 253),
('Damian Lillard', 'Portland Trail Blazers', 'PG', '6''2"', 195),
('Nikola Jokić', 'Denver Nuggets', 'C', '6''11"', 284),
('Joel Embiid', 'Philadelphia 76ers', 'C', '7''0"', 280),
('Jayson Tatum', 'Boston Celtics', 'SF', '6''8"', 210),
('Jimmy Butler', 'Miami Heat', 'SF', '6''7"', 230),
('Paul George', 'Los Angeles Clippers', 'SF', '6''8"', 220),
('Kyrie Irving', 'Dallas Mavericks', 'PG', '6''2"', 195),
('Devin Booker', 'Phoenix Suns', 'SG', '6''5"', 206),
('Donovan Mitchell', 'Cleveland Cavaliers', 'SG', '6''1"', 215),
('Zion Williamson', 'New Orleans Pelicans', 'PF', '6''6"', 284),
('Trae Young', 'Atlanta Hawks', 'PG', '6''1"', 164),
('Chris Paul', 'Golden State Warriors', 'PG', '6''0"', 175),
('Bradley Beal', 'Phoenix Suns', 'SG', '6''4"', 207),
('Ja Morant', 'Memphis Grizzlies', 'PG', '6''3"', 174),
('Jrue Holiday', 'Boston Celtics', 'PG', '6''3"', 205),
('DeMar DeRozan', 'Chicago Bulls', 'SF', '6''6"', 220),
('Karl-Anthony Towns', 'Minnesota Timberwolves', 'C', '6''11"', 248),
('Bam Adebayo', 'Miami Heat', 'C', '6''9"', 255),
('Rudy Gobert', 'Minnesota Timberwolves', 'C', '7''1"', 258),
('Klay Thompson', 'Golden State Warriors', 'SG', '6''6"', 215),
('Julius Randle', 'New York Knicks', 'PF', '6''8"', 250),
('CJ McCollum', 'New Orleans Pelicans', 'SG', '6''3"', 190),
('John Collins', 'Utah Jazz', 'PF', '6''9"', 226),
('Brandon Ingram', 'New Orleans Pelicans', 'SF', '6''8"', 190),
('Kyle Lowry', 'Miami Heat', 'PG', '6''0"', 196),
('Kristaps Porziņģis', 'Boston Celtics', 'C', '7''3"', 240),
('Tyler Herro', 'Miami Heat', 'SG', '6''5"', 195),
('Fred VanVleet', 'Houston Rockets', 'PG', '6''1"', 197),
('Jaren Jackson Jr.', 'Memphis Grizzlies', 'PF', '6''11"', 242),
('Pascal Siakam', 'Toronto Raptors', 'PF', '6''11"', 252),
('DeAaron Fox', 'Sacramento Kings', 'PG','6''3"',172),
('Russell Westbrook', 'Los Angeles Clippers', 'PG', '6''3"', 200),
('Jamal Murray', 'Denver Nuggets', 'PG', '6''4"', 215),
('Zach LaVine', 'Chicago Bulls', 'SG', '6''5"', 200),
('Brandon Ingram', 'New Orleans Pelicans', 'SF', '6''8"', 190),
('Jaylen Brown', 'Boston Celtics', 'SG', '6''6"', 220),
('Domantas Sabonis', 'Sacramento Kings', 'PF', '6''11"', 240),
('Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'SG', '6''6"', 195),
('LaMelo Ball', 'Charlotte Hornets', 'PG', '6''7"', 181),
('Deandre Ayton', 'Phoenix Suns', 'C', '6''11"', 250),
('Draymond Green', 'Golden State Warriors', 'PF', '6''6"', 230),
('D''Angelo Russell', 'Los Angeles Lakers', 'PG', '6''4"', 193),
('Tyrese Haliburton', 'Indiana Pacers', 'PG', '6''5"', 185),
('Rudy Gay', 'Utah Jazz', 'SF', '6''8"', 250),
('Jaden Ivey', 'Detroit Pistons', 'SG', '6''4"', 200),
('Jabari Smith Jr.', 'Houston Rockets', 'PF', '6''10"', 220),
('Paolo Banchero', 'Orlando Magic', 'PF', '6''10"', 250),
('Franz Wagner', 'Orlando Magic', 'SF', '6''9"', 220),
('Derrick White', 'Boston Celtics', 'SG', '6''4"', 190),
('Mikal Bridges', 'Brooklyn Nets', 'SF', '6''6"', 209),
('Jarrett Allen', 'Cleveland Cavaliers', 'C', '6''11"', 243),
('Tyrese Maxey', 'Philadelphia 76ers', 'PG', '6''2"', 200),
('Bojan Bogdanović', 'Detroit Pistons', 'SF', '6''7"', 226),
('OG Anunoby', 'Toronto Raptors', 'SF', '6''7"', 232),
('Jalen Brunson', 'New York Knicks', 'PG', '6''1"', 190),
('Miles Bridges', 'Charlotte Hornets', 'SF', '6''6"', 225),
('Clint Capela', 'Atlanta Hawks', 'C', '6''10"', 240),
('Jeremy Grant', 'Portland Trail Blazers', 'PF', '6''8"', 210),
('Spencer Dinwiddie', 'Brooklyn Nets', 'PG', '6''5"', 215),
('Tobias Harris', 'Philadelphia 76ers', 'PF', '6''7"', 226),
('Jonas Valančiūnas', 'New Orleans Pelicans', 'C', '6''11"', 265),
('Darius Garland', 'Cleveland Cavaliers', 'PG', '6''1"', 192),
('Michael Porter Jr.', 'Denver Nuggets', 'SF', '6''10"', 218),
('Evan Mobley', 'Cleveland Cavaliers', 'PF', '7''0"', 215),
('Fred VanVleet', 'Houston Rockets', 'PG', '6''1"', 197),
('Brook Lopez', 'Milwaukee Bucks', 'C', '7''0"', 282),
('Gordon Hayward', 'Charlotte Hornets', 'SF', '6''7"', 225),
('Terry Rozier', 'Charlotte Hornets', 'PG', '6''1"', 190),
('Caris LeVert', 'Cleveland Cavaliers', 'SG', '6''6"', 205),
('Christian Wood', 'Los Angeles Lakers', 'PF', '6''10"', 214),
('Jordan Poole', 'Washington Wizards', 'SG', '6''4"', 194),
('De''Andre Hunter', 'Atlanta Hawks', 'SF', '6''8"', 225),
('Mitchell Robinson', 'New York Knicks', 'C', '7''0"', 240),
('Kyle Kuzma', 'Washington Wizards', 'PF', '6''9"', 221),
('Al Horford', 'Boston Celtics', 'C', '6''9"', 240),
('Jarrett Allen', 'Cleveland Cavaliers', 'C', '6''11"', 243),
('Patrick Beverley', 'Chicago Bulls', 'PG', '6''1"', 180),
('Robert Covington', 'Los Angeles Clippers', 'SF', '6''7"', 209),
('PJ Tucker', 'Philadelphia 76ers', 'PF', '6''5"', 245),
('Marcus Smart', 'Memphis Grizzlies', 'PG', '6''3"', 220),
('Malcolm Brogdon', 'Portland Trail Blazers', 'PG', '6''5"', 229),
('Buddy Hield', 'Indiana Pacers', 'SG', '6''4"', 220),
('Aaron Gordon', 'Denver Nuggets', 'PF', '6''8"', 235),
('Myles Turner', 'Indiana Pacers', 'C', '6''11"', 250),
('Jalen Green', 'Houston Rockets', 'SG', '6''4"', 186),
('Tyler Herro', 'Miami Heat', 'SG', '6''5"', 195),
('Jusuf Nurkić', 'Phoenix Suns', 'C', '7''0"', 290),
('De''Aaron Fox', 'Sacramento Kings', 'PG', '6''3"', 185),
('Keldon Johnson', 'San Antonio Spurs', 'SF', '6''5"', 220),
('Terry Rozier', 'Charlotte Hornets', 'SG', '6''1"', 190),
('RJ Barrett', 'New York Knicks', 'SF', '6''6"', 214),
('John Wall', 'Free Agent', 'PG', '6''3"', 210),
('Derrick Rose', 'Memphis Grizzlies', 'PG', '6''2"', 200),
('Gordon Hayward', 'Charlotte Hornets', 'SF', '6''7"', 225),
('Andre Drummond', 'Chicago Bulls', 'C', '6''10"', 279),
('Kevin Huerter', 'Sacramento Kings', 'SG', '6''7"', 190),
('Cam Johnson', 'Brooklyn Nets', 'SF', '6''8"', 210),
('Jalen Suggs', 'Orlando Magic', 'SG', '6''4"', 205),
('Jalen Duren', 'Detroit Pistons', 'C', '6''11"', 250),
('Josh Giddey', 'Oklahoma City Thunder', 'SG', '6''8"', 210),
('Marvin Bagley III', 'Detroit Pistons', 'PF', '6''11"', 235),
('Jonathan Isaac', 'Orlando Magic', 'PF', '6''11"', 230),
('Wendell Carter Jr.', 'Orlando Magic', 'C', '6''10"', 270),
('Bogdan Bogdanović', 'Atlanta Hawks', 'SG', '6''6"', 220),
('Dillon Brooks', 'Houston Rockets', 'SF', '6''7"', 225),
('Harrison Barnes', 'Sacramento Kings', 'SF', '6''8"', 225),
('Kelly Oubre Jr.', 'Free Agent', 'SF', '6''7"', 203),
('Saddiq Bey', 'Atlanta Hawks', 'SF', '6''7"', 215),
('Isaiah Stewart', 'Detroit Pistons', 'C', '6''8"', 250),
('Cole Anthony', 'Orlando Magic', 'PG', '6''2"', 185),
('Alperen Şengün', 'Houston Rockets', 'C', '6''10"', 243),
('Kevin Porter Jr.', 'Houston Rockets', 'SG', '6''4"', 203),
('Kentavious Caldwell-Pope', 'Denver Nuggets', 'SG', '6''5"', 204),
('Gary Trent Jr.', 'Toronto Raptors', 'SG', '6''5"', 209),
('Markelle Fultz', 'Orlando Magic', 'PG', '6''3"', 210),
('Jakob Poeltl', 'Toronto Raptors', 'C', '7''1"', 245),
('Kevin Love', 'Miami Heat', 'PF', '6''8"', 251),
('Josh Hart', 'New York Knicks', 'SG', '6''5"', 215),
('Bruce Brown', 'Indiana Pacers', 'SG', '6''4"', 202),
('Norman Powell', 'Los Angeles Clippers', 'SG', '6''3"', 215),
('Naz Reid', 'Minnesota Timberwolves', 'C', '6''9"', 264),
('Bobby Portis', 'Milwaukee Bucks', 'PF', '6''10"', 250);

SELECT *
FROM nba_players
ORDER BY height DESC
